kind: pipeline
name: default

clone:
  depth: 1
  
steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule init && git submodule update
  
- name: build
  image: mono
  commands:
  - chmod +rwx ./build.sh
  - ./build.sh

- name: test
  image: mono
  commands:
  - chmod +rwx ./test.sh
  - ./test.sh Linux Unit
